"""empty message

Revision ID: 29dc00f91620
Revises: c7d1f7b466fe
Create Date: 2023-07-13 18:18:20.488132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dc00f91620'
down_revision = 'c7d1f7b466fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'pokemon', ['pokemon_id'], ['id'])
        batch_op.drop_column('ability')
        batch_op.drop_column('base_def')
        batch_op.drop_column('base_hp')
        batch_op.drop_column('sprite_url')
        batch_op.drop_column('base_att')
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_att', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sprite_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_hp', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_def', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ability', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pokemon_id')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
